@startuml
'https://plantuml.com/class-diagram

class CPlayer {
    +float x, y
    +void run()
    +void move()
    +void addSquare()
}

interface IWorld {
    +void addShape(IShape)
}

class CPlane(IWorld) {
    +list: IShape shapes
    +void draw()
    +void addShape(IShape shape)
}

namespace CPoint {
    class tup {
        point: namedtuple("Point", ["x", "y"])
    }
    class CPoint {
        -void __init(x, y)
        -point point = x, y
        +CPoint __add__(CPoint other)
        + __sub__(other: CPoint)
        +__repr__()
    }
}
class CSquare(IShape) {
    -void __init__(CPoint position)

    +void move(CPoint dp)
    +void draw()
}

interface IShape {
    +CPoint p0
    +void move()
    +void draw()
}

'abstract class AbstractList
'abstract AbstractCollection
'interface List
'interface Collection
'
'List <|-- AbstractList
'Collection <|-- AbstractCollection
'
'Collection <|- List
'AbstractCollection <|- AbstractList
'AbstractList <|-- ArrayList
'
'class ArrayList {
'Object[] elementData
'size()
'}
'
'enum TimeUnit {
'DAYS
'HOURS
'MINUTES
'}

@enduml